name: Complex-theme
url:

menu:
  Conocenos:
    Mision y Vision: /archives
    Miembros: /members
    Reconocimientos: /archives
  Investigación:
    Lineas de Investigación: /archives
    Proyectos: /projects
    Investigadores: /members
  Eventos:
    Seminarios: /archives
    Congresos: /projects
    Encuentros: /archives
    Conversatorios: /projects
  Aprende:
    Convocatorias: /about
  RSS: /atom.xml

footerMenu:
  Conócenos:
    Mision: /
    Vision: /
    Historia: /
    Normatividad: /
  Investigación:
    Investigadores: /
    Lineas de Investigación: /
    Proyectos: /
    Semillero: /
  Eventos:
    Seminarios: /
    Congresos: /
    Encuentros: /
    Conversatorios: /

logo: favicon.ico
favicon: favicon.ico

socials:
  twitter: icons/twitter.png
  youtube: icons/youtube.png
  facebook: icons/facebook.png
  udistrital: icons/udistrital_esc.png

# Comment
# e.g disqus: seansun
disqus:

# Analytics
mathjax: false
google_analytics:

# Copyright Infomation
copyright:
  since:
  name:
  url:
