name: Complex-theme
url:

menu:
  Conócenos:
    Misión y Visión: /conócenos
    Miembros: /miembros
    Reconocimientos: '#'
  Investigación:
    Lineas de Investigación: investigación/lineas
    Proyectos: '#'
    Investigadores: '#'
  Eventos:
    Seminarios: '#'
    Congresos: '#'
    Encuentros: '#'
    Conversatorios: '#'
  Aprende:
    Convocatorias: /convocatorias
  # RSS: /atom.xml

footerMenu:
  Conócenos:
    Mision: /conócenos
    Vision: /conócenos
    Historia: '#'
    Normatividad: '#'
  Investigación:
    Investigadores: miembros
    Lineas de Investigación: investigación/lineas
    Proyectos: '#'
    Semillero: '#'
  Eventos:
    Seminarios: '#'
    Congresos: '#'
    Encuentros: '#'
    Conversatorios: '#'

logo: favicon.ico
favicon: favicon.ico

sponsors:
  C3:
    url: https://www.c3.unam.mx/
    img: C3.png
  Universidad del Bosque:
    url: https://www.unbosque.edu.co/
    img: UEBosque.png
  Universidad Nacional:
    url: http://ciencias.bogota.unal.edu.co/gruposdeinvestigacion/caos-y-complejidad/
    img: un.png
  Universidad Pontificia Javeriana:
    url: https://ingenieria.javeriana.edu.co/investigacion/instituto/nanotecnologia
    img: Javeriana.png
  Universidad del Rosario:
    url: https://www.urosario.edu.co/
    img: URosario.png
  
socials:
  twitter: icons/twitter.png
  youtube: icons/youtube.png
  facebook: icons/facebook.png
  udistrital: icons/udistrital_esc.png

# Comment
# e.g disqus: seansun
disqus:

# Analytics
mathjax: false
google_analytics:

# Copyright Infomation
copyright:
  since:
  name:
  url:
